from enum import Enum

class Assets:
    ICON = "assets/image/icon_star_normal.png"

    EXIT = "assets/image/icon_exit.png"
    #EXIT_HOVER = "assets/image/icon_exit_hover.png"
    #EXIT_PRESSED = "assets/image/icon_exit_pressed.png"
    SETTINGS = "assets/image/icon_settings.png"
    #SETTINGS_HOVER = "assets/image/icon_settings_hover.png"
    #SETTINGS_PRESSED = "assets/image/icon_settings_pressed.png"
    HOME = "assets/image/icon_home.png"
    #HOME_HOVER = "assets/image/icon_home_hover.png"
    #HOME_PRESSED = "assets/image/icon_home_pressed.png"

    MUSIC_ON = "assets/image/icon_music_on.png"
    #MUSIC_ON_HOVER = "assets/image/icon_music_on_hover.png"
    #MUSIC_ON_PRESSED = "assets/image/icon_music_on_pressed.png"
    MUSIC_OFF = "assets/image/icon_music_off.png"
    #MUSIC_OFF_HOVER = "assets/image/icon_music_off_hover.png"
    #MUSIC_OFF_PRESSED = "assets/image/icon_music_off_pressed.png"

    SOUND_ON = "assets/image/icon_sound_on.png"
    #SOUND_ON_HOVER = "assets/image/icon_sound_on_hover.png"
    #SOUND_ON_PRESSED = "assets/image/icon_sound_on_pressed.png"
    SOUND_OFF = "assets/image/icon_sound_off.png"
    #SOUND_OFF_HOVER = "assets/image/icon_sound_off_hover.png"
    #SOUND_OFF_PRESSED = "assets/image/icon_sound_off_pressed.png"

    PVP = "assets/image/button_pvp.png"
    #PVP_HOVER = "assets/image/button_pvp_hover.png"
    #PVP_PRESSED = "assets/image/button_pvp_pressed.png"
    PVE = "assets/image/button_pve.png"
    #PVE_HOVER = "assets/image/button_pve_hover.png"
    #PVE_PRESSED = "assets/image/button_pve_pressed.png"

    THEME1 = "assets/image/button_theme1.png"
    #THEME1_HOVER = "assets/image/button_theme1_hover.png"
    #THEME1_PRESSED = "assets/image/button_theme1_pressed.png"
    THEME2 = "assets/image/button_theme2.png"
    #THEME2_HOVER = "assets/image/button_theme2_hover.png"
    #THEME2_PRESSED = "assets/image/button_theme2_pressed.png"
    THEME3 = "assets/image/button_theme3.png"
    #THEME3_HOVER = "assets/image/button_theme3_hover.png"
    #THEME3_PRESSED = "assets/image/button_theme3_pressed.png"
    THEME4 = "assets/image/button_theme4.png"
    #THEME4_HOVER = "assets/image/button_theme4_hover.png"
    #THEME4_PRESSED = "assets/image/button_theme4_pressed.png"